apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::154292417400:role/eksctl-eksdemo1-nodegroup-ng-d10da-NodeInstanceRole-zOsFnaDThoyG
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::154292417400:user/eks-user
      username: eks-user
      groups:
      - trainee-clusterrole
    - userarn: arn:aws:iam::154292417400:user/eks-developer
      username: eks-developer 
      groups:
      - developer-clusterrole
    - userarn: arn:aws:iam::154292417400:user/eks-super-admin
      username: eks-super-admin
      groups:
      - superadmin-clusterrole
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-16T06:54:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1223"
  uid: 7c584f2f-a47e-46ea-913a-7945e4db4077
