kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trainee-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets","replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list"]


---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trainee-clusterrolebinding
subjects:
- kind: User
  name: eks-user
roleRef:
  kind: ClusterRole
  name: trainee-clusterrole
  apiGroup: rbac.authorization.k8s.io